services:
  - type: web
    name: telegram-user-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python user_bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: API_MONGO_URL
        sync: false
      - key: API_RAG_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: USE_REDIS
        value: "true"
      - key: PORT
        value: "8080"
    autoDeploy: true 